obj-y += calc.o
obj-y += ps.o
obj-y += nodefuncs.o
obj-y += reserve.o
obj-y += hr_timer_func.o
obj-y += sysfs.o
obj-y += partition_scheduling.o
obj-y += suspension_framework.o
obj-y += switches.o
obj-y += linked_list.o
obj-y += bin_packing.o
obj-y += bin_linked_list.o
obj-y += cpu_linked_list.o
obj-y += energy_saving.o
obj-y += custom_heuristic.o

